---
basic:
  - name: Title
    definition: Human-readable name
    json: title
    rdfa: dct:title

  - name: Description
    definition: Human-readable description
    json: description
    rdfa: dct:description


expanded:

  - name: Release Date
    definition: Date of issuance
    json: issued
    rdfa: dct:issued

  - name: Related Documents
    definition: Related material
    json: references
    rdfa: dcat:distribution
